name: C/C++ CI (Windows)

on: [push, pull_request]

jobs:
  build-win:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build with MSVC
      shell: cmd
      run: workflow_build_windows.bat

    - uses: actions/upload-artifact@v2
      with:
        name: DCue for Windows
        path: build\dcue.7z
      name: upload-dcue-build