name: Build and test (Linux)

on: [push, pull_request]

jobs:
  test-lnx:
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Install curl
      run: sudo apt-get update && sudo apt-get install libcurl4-openssl-dev ninja-build

    - name: Build and test (Debug)
      run: .github/lnx_build_and_test.sh Debug

    - name: Build and test (Release)
      run: .github/lnx_build_and_test.sh Release
